### ISSUE TITLE
The data.zip file

### ISSUE THREAD

**Issue by ZihaoLin0123** [ZeroYuHuang/Transformer-Patcher#2]
Hi, thanks for your nice work!

I wonder could you share the data file you mentioned [here](https://github.com/ZeroYuHuang/Transformer-Patcher#data)? I downloaded the fever but found the format is different form what you implement in the fever_dataloader.py file.

Thanks!

**Comment by ENSCMA2** [comment]
Hi @ZihaoLin0123, did you find a solution to this? I'm wondering the same thing.
